# Generated by Django 6.1 on 2026-08-11 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('event_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('host', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
                ('severity', models.CharField(max_length=50)),
                ('detection_rule', models.CharField(max_length=255)),
                ('rule_id', models.CharField(max_length=255)),
                ('mitre_tactic', models.CharField(max_length=255)),
                ('mitre_technique', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.case')),
            ],
        ),
    ]
