# Generated by Django 6.1 on 2026-09-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_evidencefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencefile',
            name='sha256',
            field=models.CharField(blank=True, default='', help_text='Hex SHA-256 digest of the original evidence file contents. Empty when the hash has not been computed.', max_length=64),
        ),
    ]
