# Generated by Django 6.1 on 2026-09-30

import hashlib
from pathlib import Path

from django.conf import settings
from django.db import migrations


def _sha256(path):
    """Hex SHA-256 of a file, streamed in chunks."""
    digest = hashlib.sha256()
    with open(path, "rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _resolve(relative_path):
    """Resolve a stored path inside EVIDENCE_ROOT or return None."""
    root = Path(settings.EVIDENCE_ROOT).resolve()
    candidate = (root / relative_path).resolve()

    try:
        candidate.relative_to(root)
    except ValueError:
        return None

    if not candidate.exists() or not candidate.is_file():
        return None

    return candidate


def backfill_evidence_sha256(apps, schema_editor):
    """Hash existing evidence files that do not yet have a stored SHA-256.

    Records whose on-disk file is missing, inaccessible, or whose stored
    path escapes EVIDENCE_ROOT keep an empty hash rather than fabricating
    one.
    """
    EvidenceFile = apps.get_model("core", "EvidenceFile")

    for evidence in EvidenceFile.objects.filter(sha256="").iterator():
        path = _resolve(evidence.file_path)
        if path is None:
            continue
        try:
            evidence.sha256 = _sha256(path)
        except OSError:
            continue
        evidence.save(update_fields=["sha256"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_evidencefile_sha256"),
    ]

    operations = [
        migrations.RunPython(backfill_evidence_sha256, noop),
    ]