# Generated by Django 6.1 on 2026-09-30 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_evidencefile_backfill_sha256'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SigmaDetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sigma_detection_results', to='core.case')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sigma_detection_results', to=settings.AUTH_USER_MODEL)),
                ('evidence_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sigma_detection_results', to='core.evidencefile')),
            ],
        ),
    ]
